config/routes.rb
CookBook::Application.routes.draw do
  resources :books, :recipes, :ingredients, :users, :sessions

  root to: 'books#index'

  get '/signup' => 'users#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  get'/signin' => 'sessions#new'

  get '/forgot' => 'users#forgot_password'
  post '/send_reset' => 'users#send_reset'
  get '/reset/:token' => 'users#reset_password'

end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  course       :string(255)
#  cooktime     :integer
#  servingsize  :integer
#  instructions :text
#  image        :text
#  book_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Recipe < ActiveRecord::Base
  belongs_to :book
  has_and_belongs_to_many :ingredients
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :signed_in_user, only: [:create, :new, :edit, :update]

  def index
    @recipes = Recipe.all
  end
  def new
    @recipe = Recipe.new
  end
  def create
    new_recipe = params.require(:recipe).permit(:name, :course, :cooktime, :servingsize, :instructions, :image, :book_id, :ingredient_ids)
    recipe = Recipe.create(new_recipe)
    redirect_to(recipe)
  end
  def show
    @recipe = Recipe.find(params[:id])
  end
  def edit
    @recipe = Recipe.find(params[:id])
  end
  def update
    recipe = Recipe.find(params[:id])
    recipe.update_attributes(params[:recipe])
    redirect_to(recipe)
  end
  def destroy
    recipe = Recipe.find(params[:id])
    recipe.delete
    redirect_to(recipes_path)
  end
end

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :autofocus => true %>
  <br>
  <%= f.label :course %>
  <%= f.text_field :course %>
  <br>
  <%= f.label :cooktime %>
  <%= f.text_field :cooktime %>
  <br>
  <%= f.label :servingsize %>
  <%= f.text_field :servingsize %>
  <br>
  <%= f.label :instructions %>
  <%= f.text_field :instructions %>
  <br>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <br>
  <div class="input-group">
    <% Ingredient.order(:name).each do |ingredient| %>
      <span class="input-group-addon"><%= ingredient.name %>
      <%= check_box_tag 'recipe[ingredient_ids][]', ingredient.id, ingredient.in?(@recipe.ingredients.to_a), {class: "checkbox inline"} %>
      </span>
    <% end %>
  </div>
  <p><p>
  <%= f.submit  class: "btn btn-primary" %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render :partial => 'form' %>

app/views/recipes/index.html.erb
<ul class="nav nav-pills">
  <li>
    <%= link_to('New Recipe', new_recipe_path) %>
  </li>
</ul>


<% @recipes.each do |recipe| %>
  <div class="row">
     <div class="col-md-4 col-sm-4">
      <p class="lead"><%= link_to(recipe.name, recipe) %>
      <p><%= recipe.course %>
      <p><%= recipe.cooktime %>
      <p><%= recipe.servingsize %><
      <p><%= recipe.instructions %>
    </div>
     <div class="col-md-8 col-sm-8">
      <p><%= image_tag(recipe.image) %>
    </div>
  </div>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render :partial => 'form' %>

app/views/recipes/show.html.erb
<ul class="nav nav-pills">
  <li><%= link_to('New Recipe', new_recipe_path) %></li>
  <li><%= link_to('Edit Recipe', edit_recipe_path(@recipe)) %></li>
  <li><%= link_to('Delete Recipe', @recipe, :method => :delete, :confirm => 'Are you sure?') %></li>
  <div class='spacer'></div>
</ul>

<div class="row">
  <div class="col-md-5 col-sm-5">
    <p class="lead"><%= @recipe.name %></p>
    <%= image_tag(@recipe.image) %>
  </div>

  <div class="col-md-7 col-sm-7">
    <% @recipe.ingredients.each do |ingredient| %>
      <%= ingredient.name %>
      <%= image_tag(ingredient.image,  size: "40x40") %>
    <% end %>
  </div>
 </div>