config/routes.rb
CookBook::Application.routes.draw do
  resources :books, :recipes, :ingredients, :users, :sessions

  root to: 'books#index'

  get '/signup' => 'users#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  get'/signin' => 'sessions#new'

  get '/forgot' => 'users#forgot_password'
  post '/send_reset' => 'users#send_reset'
  get '/reset/:token' => 'users#reset_password'

end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  measurement :string(255)
#  cost        :decimal(, )
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Ingredient < ActiveRecord::Base
  has_and_belongs_to_many :recipes
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :new, :edit, :update]

  def index
    @ingredients = Ingredient.all
  end
  def new
    @ingredient = Ingredient.new
  end
  def create
    new_ingredient = params.require(:ingredient).permit(:name, :measurement, :cost, :image)
    @ingredient = Ingredient.create(new_ingredient)
    render :show
  end
  def show
    @ingredient = Ingredient.find(params[:id])
  end
  def edit
    @ingredient = Ingredient.find(params[:id])
  end
  def update
    @ingredient = Ingredient.find(params[:id])
    @ingredient.update_attributes(params[:ingredient])
    render :show
  end
  def destroy
    ingredient = Ingredient.find(params[:id])
    ingredient.delete
    redirect_to(ingredients_path)
  end
end

app/views/ingredients/_form.html.erb
<%= form_for @ingredient do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :autofocus => true %>
  <br>
  <%= f.label :measurement %>
  <%= f.text_field :measurement %>
  <br>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <br>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <br>
  <p><p>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Edit Ingredient</h1>
<%= render :partial => 'form' %>

app/views/ingredients/index.html.erb
<ul class="nav nav-pills">
  <li>
<%= link_to('New Ingredient', new_ingredient_path) %>
  </li>
</ul>

<table class="table .table-striped">
<% @ingredients.each do |ingredient| %>
  <tr>
    <td>
        <p class="lead"><%= link_to(ingredient.name, ingredient) %>
        <p><%= ingredient.measurement %>
        <p><%= number_to_currency ingredient.cost %>
      </td>
    <td>
      <%= image_tag(ingredient.image, size: "100x100") %>
    </td>
</tr>
<% end %>
</table>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>
<%= render :partial => 'form' %>

app/views/ingredients/show.html.erb
<ul class="nav nav-pills">
  <li><%= link_to('New Ingredient', new_ingredient_path) %></li>
  <li><%= link_to('Edit Ingredient', edit_ingredient_path(@ingredient)) %></li>
  <li><%= link_to('Delete Ingredient', @ingredient, :method => :delete, :confirm => 'Are you sure?') %></li>
</ul>

<div class="row">
  <div class="col-md-3 col-sm-3">
   <p class="lead"><%= @ingredient.name %>
   <p><%= @ingredient.measurement %>
   <p><%= number_to_currency @ingredient.cost %>
  </div>
  <div class="col-md-8 col-sm-8">
    <%= image_tag(@ingredient.image) %>
  </div>
</ul>