config/routes.rb
CookBook::Application.routes.draw do
  resources :books, :recipes, :ingredients, :users, :sessions

  root to: 'books#index'

  get '/signup' => 'users#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  get'/signin' => 'sessions#new'

  get '/forgot' => 'users#forgot_password'
  post '/send_reset' => 'users#send_reset'
  get '/reset/:token' => 'users#reset_password'

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  cuisine    :string(255)
#  chef       :string(255)
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer

class Book < ActiveRecord::Base
  has_many :recipes
  belongs_to :user
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include BooksHelper

  before_filter :signed_in_user, only: [:create, :new, :edit, :update]
  before_filter :check_book_owner, only: [:destroy, :update, :edit]

  def index
    @books = Book.all
  end
  def new
    @book = Book.new
  end
  def create
    new_book = params.require(:book).permit(:title, :cuisine, :chef, :image,:recipes)
    new_book[:user_id]= current_user.id
    @book = Book.create(new_book)
    render :show
  end
  def show
    @book = Book.find(params[:id])
  end
  def edit
    @book = Book.find(params[:id])
  end
  def update
    @book = current_user.books.where(:id => params[:id])
    @book.update_attributes(params[:book])
    render :show
  end
  def destroy
    book = current_user.books.where(:id => params[:id])
    
    book.delete
    redirect_to(books_path)
  end

end

app/helpers/books_helper.rb
module BooksHelper
	def check_book_owner
		book = current_user.books.where(:id => params[:id]).first
    	if book.nil?
    		flash[:error] = "That's not your book."
			redirect_to book_path(params[:id])
		end
	end
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :autofocus => true %>
  <br>
  <%= f.label :cuisine %>
  <%= f.text_field :cuisine %>
  <br>
  <%= f.label :chef %>
  <%= f.text_field :chef %>
  <br>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <br>
  <div class="input-group">
    <% Recipe.order(:name).each do |recipe| %>
       <span class="input-group-addon">
        <%= recipe.name %>
        <%= check_box_tag 'book[recipe_ids][]', recipe.id, recipe.in?(@book.recipes), {class: "checkbox inline"} %>
        </span>
    <% end %>
  </div>
  <p><p>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<ul class="nav nav-pills">
  <li>
    <%= link_to('New Book', new_book_path) %>
  </li>
</ul>

<% @books.each do |book| %>
  <div class="row">
     <div class="col-md-3 col-sm-3">
      <p class="lead"><%= link_to(book.title, book) %></p>
      <p class="text-info"><%= book.cuisine %></p>
      <p class="text-warning"><%= book.chef %></p>
    </div>
    <div class="col-md-8 col-sm-8">
      <%= image_tag(book.image) %>
    </div>
  </div>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<ul class="nav nav-pills">
  <li><%= link_to('New Book', new_book_path) %></li>
  <li><%= link_to('Delete Book', @book, :method => :delete, :confirm => 'Are you sure?') %></li>
  <li><%= link_to('Edit Book', edit_book_path(@book)) %></li>
</ul>

<div class="row">
     <div class="col-md-3">
      <p class="lead"><%= link_to(@book.title, @book) %></p>
      <p class="text-info"><%= @book.cuisine %></p>
      <p class="text-info"><%= @book.chef %></p>
      <p class="text-info">Uploaded by: <%= @book.user.name %></p>
    </div>
    <div class="col-md-8">
      <p class="text-warning"><%= image_tag(@book.image) %></p>
    </div>
</div>

<br>
<% @book.recipes.each do |recipe| %>
    <p>&nbsp;</p>
  <div class="row">
    <div class="col-md-5 col-sm-5">
      <p class="lead"><%= recipe.name %></p>
      <%= image_tag(recipe.image) %>
    </div>

    <div class="col-md-7 col-sm-7">
      <% recipe.ingredients.each do |ingredient| %>
        <%= ingredient.name %>
        <%= image_tag(ingredient.image,  size: "40x40") %>
      <% end %>
    </div>
   </div>
<% end %>