config/routes.rb
CookBook::Application.routes.draw do
  resources :books, :recipes, :ingredients, :users, :sessions

  root to: 'books#index'

  get '/signup' => 'users#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  get'/signin' => 'sessions#new'

  get '/forgot' => 'users#forgot_password'
  post '/send_reset' => 'users#send_reset'
  get '/reset/:token' => 'users#reset_password'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">Le Cook Book App</a>
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar">ddd</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <div class="navbar-header navbar-right">
    <% if signed_in? %>
      <p class="navbar-text">
        <%= link_to "My profile", current_user %>
      </p>
      <p class="navbar-text">
        <%= link_to "Sign out", signout_path, method: "delete" %>
      </p>
    <% else %>
      <p class="navbar-text">
        <%= link_to "Sign up", signup_path %>
      </p>
      <p class="navbar-text">
        <%= link_to "Sign in", signin_path %>
      </p>
    <% end %>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to('Books', books_path) %></li>
      <li><%= link_to('Recipes', recipes_path) %></li>
      <li><%= link_to('Ingredients', ingredients_path) %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook</title>
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
  <script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <%= render 'layouts/header' %>
    <div class="row">
      <div class="col-md-12 col-sm-12">
        <%flash.each do|key,value|%>
                <div class="alert alert-<%=key%>"> <%=value%> </div>
        <%end%>
        <%= yield %>
      </div>
    </div>
</div>

</body>
</html>